### PR TITLE
Campaign mission title

### PR DESCRIPTION
**Pull request by Alexandr57**
Add the ability to specify the title of the mission separately for each company rather than globally for all

Changes:
image
image
image
image

If the title of missions to be found will be displayed in the campaign libx file it if not that of a standard file

### CODE REVIEW

**Comment by lewinjh** [comment]
Why would campaigns need a different mission title? Isn't "Mission %d" fine for all of them?

**Comment by Alexandr57** [comment]
lewinjh
Superfluous just will not.
For example if you want to kartodel in his campaign instead Mission 1 was Chapter 1, and not to change the main file.

**Comment by Alexandr57** [comment]
Also, my method allows not show
Mission 1
and for example
Mission 1 of 10
Suffice it to libx campaign file write:
3:Mission %d of 10

So this feature is quite useful

**Comment by Kromster80** [comment]
@lewinjh I guess it's a nice feature to have, as Alexadr shows in examples.

**Pull request merged**
