### PR TITLE
"Unit is hungry" message could be shown for invalid/dead groups

### PR DESCRIPTION
**Pull request by andreus791**
As described by Kistrel, see issue #20.

### CODE REVIEW

**Comment by lewinjh** [comment]
Thanks! Does this resolve the underlying problem behind Kistrel's issue though? Does the TKMGroup eventually get removed or is there another bug where the unit dies but you end up with an empty group that sticks around?

**Comment by andreus791** [comment]
Seems group is alive because it has at least one member. This member is dying and still can be accessed. So game checks dying members (they probably have condition and another attributes <= 0) and sends message. The same thing happens sometimes when unit dies in game because of hunger (if hunger message check and death happen at the same tick, player gets message). Checked code - any valid group should be removed when dies in UpdateState.

Then checked with actions.log
previous script, plus:

procedure onwarriorequipped(u,g:integer);
begin
  Actions.Log('Groups successfully created. Group ID: ' + IntToStr(g) + '; Members: ' + IntToStr(States.GroupMemberCount(g)) + '; Member IDs: ' + IntToStr(u));
end;

procedure OnUnitDied(id,ak:integer);
begin
  Actions.Log('Group dies. Group ID: ' + IntToStr(states.unitsgroup(id)) + '; Member IDs: ' + IntToStr(id));
end;

procedure onplanroadplaced(p,x,y:integer);
var i:integer; gg:array of integer;
begin
actions.planremove(p,x,y);
gg := states.playergetallgroups(0);
actions.log('Current state: ' + inttostr(length(gg)) + ' groups found');
if length(gg) > 0 then
for i := 0 to length(gg) - 1 do
actions.log('Groups: ' + inttostr(gg[i]));
end;

2016.11.17 10:54:03.645   Current state: 0 groups found
2016.11.17 10:54:06.284   Group dies. Group ID: -1; Member IDs: 12058160
2016.11.17 10:54:07.371   Groups successfully created. Group ID: 4046371; Members: 1; Member IDs: 12058160
2016.11.17 10:54:09.774   Current state: 1 groups found
2016.11.17 10:54:09.774   Groups: 4046371

Group is saved somewhere in array and can be accessed, f.e in states.groupdead script.
According to log, group dies before it was created.

**Comment by reyandme** [comment]
Pls fix this:
KM_UnitGroups.pas(1438,5) Fatal: Syntax error, "THEN" expected but "BEGIN" found

**Comment by andreus791** [comment]
fixed in PR #134

**Pull request merged**
