### PR TITLE
Add the ScriptValidatorCLI util

### PR DESCRIPTION
**Pull request by LauraRozier**
Created to use as validator for a website that has a scripting 'playground'
Tested with Wine and that works perfectly fine.

### CODE REVIEW

**Comment by Kromster80** [comment]
I'm not convinced this should be a standalone util.
Why not add the CLI to existing ScriptValidator instead?

**Comment by Alexandr57** [comment]
In RAD Studio there is no CLI there FMX

**Comment by LauraRozier** [comment]
@Alexandr57 I'm sure you can make Console Apps in RAD, even in Tokyo Starter. :)
@Kromster80 Will look at how to implement that properly. (Already have an idea)

**Comment by LauraRozier** [comment]
New repo + PR will follow shortly.

**Comment by Alexandr57** [comment]
Не знаю как это работает но если через батник написать так C:\Games\KaM Remake\Campaigns\An Empire Destroyed\AED01\AED01.script
Возникает ошибка.

I do not know how it works, but if I write through the batch file as C: \ Games \ KaM Remake \ Campaigns \ An Empire Destroyed \ AED01 \ AED01.script
An error occurs.

image

**Pull request closed without merging**
