### PR TITLE
Dynamic Scripts: added support for ogg audio format

### PR DESCRIPTION
**Pull request by reyandme**

### CODE REVIEW

**Comment by reyandme** [comment]
#282 implementation

**Comment by Kromster80** [comment]
I wanted to ask about OGG license stuff. Do we need to do anything special about it? (mention in readme, add disclaimers, etc.)

**Comment by reyandme** [comment]
Is there any chance this PR will be reviewed one day ?

**Comment by Kromster80** [comment]
Please respond in linked Issue #282 first.

**Pull request closed without merging**
