### PR TITLE
Allow to save and use last entered password

### PR DESCRIPTION
**Pull request by andreus791**
#15
Maybe similar option for lobby description could be useful.

### CODE REVIEW

**Comment by Kromster80** [comment]
Storing plane passwords sounds like a bad idea. I don't recall other games offering such function.

**Comment by Kromster80** [comment]
@lewinjh what do you say?

**Comment by lewinjh** [comment]
Well these aren't private account passwords, just a codeword shared amongst friends to let you enter the room, so security isn't such a big issue. I wouldn't expect people to reuse their Gmail password here since they have to tell it to their friends ;)

As for the feature, I don't really have an objection. I guess if you're often creating lobbies for the same group of friends it would be annoying typing in the password every time? (I assume you implemented it because it's a feature you'd like to see as a player)

**Comment by andreus791** [comment]
As a player I often create rooms with the same password. And yes, I'd like to see this feature

**Comment by Kromster80** [comment]
Okay then, I'm in :-)

**Comment by Kromster80** [comment]
Maybe it is better to rename the label / variables to "Remember password"
Also immediately erase password when player unchecks the checkbox

**Comment by Kromster80** [comment]
@andreus791 please see if you can do this part too: "Also immediately erase password when player unchecks the checkbox"

**Pull request merged**
