### PR TITLE
Update position in sp game list on maped game save

### PR DESCRIPTION
**Pull request by reyandme**
Could be usufull for mapmakers, when they edit SP map (or campaign map, which is usually edited as SP map). Then if they want to test their changes map will be already selected in list.

For all other players it could not add any difficulties, because it not often to play same SP map all the time and also they probably do not use MapEd so much.

If mapmakers want to check their MP map changes, they could use 'favorite maps' feature - they are updated on maped resave

### CODE REVIEW

**Comment by Kromster80** [comment]
It would be much better to add a button into MapEd [Play this mission] instead.

**Comment by reyandme** [comment]
Yes, it's a good alternative. We can add this button to the last menu (save/load)

**Comment by Kromster80** [comment]
Let's do that instead :)

**Comment by reyandme** [comment]
Ok !

**Pull request closed without merging**
