### PR TITLE
Update - Added parser tool

### PR DESCRIPTION
**Pull request by LauraRozier**
Added a small tool to scan files to create a table layout for wikis.

### CODE REVIEW

**Comment by Kromster80** [comment]
Please remove mes and res files from PR
Also remove src\ folder, pas/dfm files will be just fine in the main folder )

**Comment by LauraRozier** [comment]
Sure thing :)

**Comment by LauraRozier** [comment]
Finished.
For some reason the .pas and .dfm files got completely ignored by Git.. 
Happened since the most recent update.

**Comment by Kromster80** [comment]
Thanks! :-)

**Comment by LauraRozier** [comment]
No problem at all. :)

**Pull request merged**
