### PR TITLE
Replay/Spectate - separated and sorted by teams list of hands

### PR DESCRIPTION
**Pull request by reyandme**
Also added new funtion to get teams from hands alliances info

Here how it looks like:

image

### CODE REVIEW

**Comment by Kromster80** [comment]
This takes too much space IMO. Why not make just a plain list?

Team1 - Player1
Team1 - Player3
Team2 - Player4
Team2 - Player5
Team3 - Player6

**Comment by reyandme** [comment]
I think separating looks better, than list with 2 columns. Its easier to read - eye can separate teams visually without finding and reading team label. Its logical dividing of monotone space.

Also 4 teams is the maximum, usually its 2 teams only.
 
And if we write Team 1 - Player 1 it will also take lots of space - not in height, but in width.

Another option - do not write "Team 1" - make just plain separator, lets say 1-5px height.

img

Also we can ask on kam.net, as always, I've already create topic there.

**Comment by reyandme** [comment]
I've made separators 5px height - as on screenshot above

**Comment by Kromster80** [comment]
About the separators, can you make them darker and without white outline using existing methods?

**Comment by reyandme** [comment]
Here it is:

img

**Comment by lewinjh** [comment]
Looks good to me, it will make it easier to see what is going on in replays

**Pull request merged**
