### PR TITLE
Map Editor: when select tile with eyedropper, scroll to this tile in tile table

### PR DESCRIPTION
**Pull request by reyandme**

### CODE REVIEW

**Comment by lewinjh** [comment]
It looks like the new line format was changed in the files KM_InterfaceMapEditor.pas and KM_GUIMapEdTerrainTiles.pas. This makes diffs hard to read and messes up blame history. Could you please change them back to the format they were in before? (I believe we use Windows format) If we are not being consistent across our .pas files then please submit a different pull request to fix it.

**Comment by reyandme** [comment]
After #236 I start facing this problems after merge from kromster80/master into my other branches with at least KM_InterfaceMapEditor.pas
I fixed all the PRs and now, after another merge it comes here again.

**Comment by lewinjh** [comment]
That's annoying... It must have been switched somehow. The GitHub editor built into the website probably uses Linux style new lines, so maybe someone used that for a minor correction and it messed it up? Notepad++ lets you check and change it under Edit -> EOL Conversion.

**Comment by reyandme** [comment]
#245 is going to fix cr lf for KM_InterfaceMapEditor.pas and KM_GUIMapEdTerrainTiles.pas

**Pull request merged**
