### PR TITLE
BugFix - house collection keep link to house after deleting. 

### PR DESCRIPTION
**Pull request by reyandme**
So even without houses you can get Houses.Count > 0 and Hand.HasAssets wil be true, you will see hand center screen/can make ally etc etc etc

### CODE REVIEW

**Comment by Kromster80** [comment]
Looks like more refactoring/simplification could be done here.

**Comment by reyandme** [comment]
I do not think refactoring is a good thing to do while bug fixing. Refactoring could produce new bugs and it will need much more time for testing.
Its better to do in a separate branch.

**Comment by Kromster80** [comment]
Isn't there a way to use gHands.HitTestHouse(Position) or alike and delete the house properly only once, instead of keeping using the inefficient and lengthy loop?

**Comment by reyandme** [comment]
I missed that HousesHitTest method - too many HitTest's everywhere.
It was not used before this PR

**Pull request merged**
