### PR TITLE
Chat mute player btn

### PR DESCRIPTION
**Pull request by reyandme**
Added ability to mute annoying player in chat (both lobby chat and game chat).

1. UI:
a) Here how it looks in game chat (icons left from the player flags): [in game](https://puu.sh/sNGzb/8866b0895d.png)
(this screenshot is made just to show how it looks like, ofc AI players and player itself can't be muted).
Icons are clickable, have dynamic hints (Mute or Unmute player) (dynamic means when you press on Icon its hint changes). To let dynamic hints work better there is another small PR #153.

b) In lobby chat mute player is possible from player menu, by pressing on his flag. 
[For host added 1 line in menu](https://puu.sh/sNHmx/abd030b6b4.png)
[For joiner menu consists only of that line](https://puu.sh/sNHpA/cae506ec79.png)
When player is muted line in menu changes and his flag color is [darkened](https://puu.sh/sNHCI/835859a501.png)

2. Game behaviour: If player is muted by another player then any of his chat messages do not appears. Also it prevents beacons.

3. Imlementation: 
Info about muted player stored in TKMNetPlayerInfo and transfered between all players

New method added to UpdateItem in TKMPopUpMenu.

To calc player menu width in lobby added new method GetMaxPrintWidthOfStrings, which calc max width of specified array of Strings with specified Font.

### CODE REVIEW

**Comment by reyandme** [comment]
Now when player A is muted by player B the only way player A can noticed that is by trying to whisper to player B - there will be no such option in list. Probably its enought. No need to put some extra icons for that on the Allies panel.
@lewinjh @Kromster80 what do you think ?

**Comment by Kromster80** [comment]
"Info about muted player stored in TKMNetPlayerInfo and transfered between all players" - why does it need to be transferred between players? I was thinking that when A mutes B, it means just that A receives messages from B, but they are not displayed, without ever requiring introduction of "mk_MutePlayer".

Please explain the design behind this PR changes.

**Comment by Kromster80** [comment]
As discussed, @reyandme will refactor this PR.

**Comment by reyandme** [comment]
New PR #199 created instead of this one for convenience reasons

**Pull request closed without merging**
