### PR TITLE
[WIP] Owner changing via scripts

### PR DESCRIPTION
**Pull request by LauraRozier**
This PR brings what was requested in issue " Dynamic script to change house/unit owner #74 ".
Tested with the included map.

Might still require attention as hands also contain refs to unit/group/house pointers?

### CODE REVIEW

**Comment by Kromster80** [comment]
This needs much more work and checking. I would not recommend to implement all 3 at once.

**Comment by lewinjh** [comment]
There are lots of tricky cases to consider here which could cause unexpected situations, bugs or crashes:
- Units eating inside inn, inn owner is changed
- Unit working in house or out in fields, house owner is change but unit continues to live/work there even though it belongs to a different team
- Unit working in house or out in fields, unit owner changes, unit continues to live/work in house owned by different team
- Serf is carrying goods to a house, house owner is changed
- Houses register their supply/demand in delivery queue. House owner changes. House supply/demand is still registered in delivery queue for the wrong team. Deliveries to/from house still happen by serfs for old team not new team. Crashes will probably occur when the house tries to update the supply/demand.
- Serf is performing delivery, serf owner changes, serf's task's delivery ID is now invalid in the new team's delivery queue
- Recruit living in barracks, recruit owner is changed
- Labourer waiting for stone to build road, labourer owner is changed
- Two groups of soldiers are fighting, owners are changed to same team, units are now fighting units from their own team
- Food has been ordered for soldiers, soldiers team is changed
- etc. etc.

You could even have enemy units living inside your houses if they were changed to an enemy team.

The reason we didn't implement this previously and told people to "destroy and recreate" is because there's so many cases like this to solve. It's much neater to destroy the old unit/house and create a new one. All these loose ends are tied up through the destruction of the old unit/house.

I'm not sure it's worth trying to solve all of these cases since it will make the code more complicated/messy/hard to maintain (would we always have to assume everywhere that ownership can change at a moment's notice? Hard to do). Maybe you could implement a clean "destroy and recreate" solution as script actions?

**Comment by LauraRozier** [comment]
That might be a better way indeed.
Silent destroy followed by a create at the same exact coordinates/state/etc.
One thing to think about then is, how to handle goods inside houses?
Just discard them or re-add them?

**Comment by Kromster80** [comment]
Recreating state is often impossible, since it depends on many external variables, as Lewin extensively pointed out. For houses, e.g. I suppose only basic properties could be passed by (wares, damage).

If you are inclined to make this PR work, then I'd remove anything but the houses for start. Also note that scripting class should do as little as possible. Method likely should go into TKMHands.HouseOwhenChange(aOldOwner, aNewOwner: TPlayerIndex);

**Comment by LauraRozier** [comment]
The most recent push only contains the HouseOwnerChange.
It stores and re-uses the following values:

``` Pascal
houseDmg: Word;
housePos: TKMPoint;
houseType: THouseType;
houseState: THouseState;
```

Now I just need to find a way to store the wares.
Though for Barracks and warehouses this might become complicated again.

**Comment by LauraRozier** [comment]
Maybe this would be something that could be used?
Sample code image

**Comment by Kromster80** [comment]
The most recent push contains all the resulting changes made in this PR (including units and groups functions you have added).

What does HouseState store?

**Comment by LauraRozier** [comment]
My bad, this should be THouseBuildState, not THouseState.
Will be updated in the next push.
I should have also stated that the other ones are commented out, so technically still there.

To be honest I am not sure if one would even want to allow the house to be transferred when the TKMHouse.BuildingState is not 'hbs_Done'.

Right now the code doesn't allow the player to.

**Comment by Kromster80** [comment]
I'm closing this PR for reasons well outlined by Lewin.

**Pull request closed without merging**
